### ISSUE TITLE
Saying Expiry Year is invalid Expiration year. Something missing in Android?

### ISSUE THREAD

**Issue by dhiwakarmani** [bambora/na-android-checkout#13]
{
  "message": "Something went wrong with beanstream single payment process",
  "errors": {
    "code": 314,
    "category": 3,
    "message": "Missing or invalid payment information - Please validate all required payment information.",
    "reference": null,
    "details": [
      {
        "field": "card:expiry_year",
        "message": "Invalid expiration year"
      }
    ],
    "status": 400
  }
}

**Comment by svenresch** [comment]
This was fixed in the latest release.
