### ISSUE TITLE
Could not found bic_artifactory_user , while build the project

### ISSUE THREAD

**Issue by nrup-parikh-indianic** [bambora/na-android-checkout#24]
Error:(61, 0) Could not get unknown property 'bic_artifactory_user' for object of type org.jfrog.gradle.plugin.artifactory.dsl.DoubleDelegateWrapper.

**Comment by svenresch** [comment]
Hi. Sorry but we do not provide support for building this project as it is built and deployed to a Gradle compliant repository in jFrog.io that we manage. Feel free to follow the instructions given in the main ReadMe to be able to use the pre-built library artifact in your project.
